baseURL = "https://sua.sh/"
enableGitInfo = true
languageCode = "en-us"
theme = "ananke"
title = "blog"

[caches]
[caches.images]
dir = ":cacheDir/images"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
